name=MAX7219Display
version=0.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=MAX7219 8-digit 7-Segment LED display driver
paragraph=**PRELIMINARY**
category=Display
includes=MAX7219Display.h
url=https://github.com/mumanchu/MAX7219Display
architectures=*
